name: 'revops_pilot'
version: '1.0.0'
config-version: 2
profile: 'revops_pilot_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  revops_pilot:
    materialized: table
    staging:
      materialized: ephemeral
